npm install express
npm install ws
npm install wss
npm install cluster
npm install http
npm install helmet
npm install cors
npm install morgan
npm install body-parser
npm install compression
npm install dotenv
npm install https
npm install tailwindcss
npm install postcss
npm install autoprefixer
npm install next.js
npm install tsconfig
npm install babel
npm install prettier